# See: https://taskfile.dev/api/

# Arch install AUR:
# yay -S go-task-bin

# > go-task generate

version: '3'

tasks:
  generate:
    aliases:
      - gen
    desc: 'Generate code from proto files'
    cmds:
      - protoc -I proto proto/auth/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/api/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative

  test:
    aliases:
      - t
    desc: 'Run tests'
    cmds:
      - go test -v ./...
